name: "iNoteBookCiCD"
services:
  frontend:
    image: ${DOCKER_FRONTEND_IMAGE_NAME}
    environment:
      - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
    ports:
      - 3000:3000
    profiles: ["ui"]
  
  backend-1:
    image: ${DOCKER_BACKEND_IMAGE_NAME}
    environment:
      - URL=${DATABASE_URL}
      - JWT_SECREATE_KEY=${JWT_SECRET_KEY}
    ports:
      - 5000:3000
    volumes:
      - ./userimg:/app/temp
    depends_on:
      - mongo
    networks:
      - i_notebook_network

  backend-2:
    image: ${DOCKER_BACKEND_IMAGE_NAME}
    environment:
      - URL=${DATABASE_URL}
      - JWT_SECREATE_KEY=${JWT_SECRET_KEY}
    ports:
      - 5001:3000
    volumes:
      - ./userimg:/app/temp
    depends_on:
      - mongo
    networks:
      - i_notebook_network
  backend-3:
    image: ${DOCKER_BACKEND_IMAGE_NAME}
    environment:
      - URL=${DATABASE_URL}
      - JWT_SECREATE_KEY=${JWT_SECRET_KEY}
    ports:
      - 5002:3000
    volumes:
      - ./userimg:/app/temp
    depends_on:
      - mongo
    networks:
      - i_notebook_network
  
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db:rw  #
    networks:
      - i_notebook_network

networks:
  i_notebook_network:
    driver: bridge
